### ISSUE TITLE
Make database connection settings configurable

### ISSUE THREAD

**Issue by cybercamphackathon** [CodigoSeguro/PhishingFisher#4]
* Do not hardcode or commit passwords

private string MyConnection2 = "datasource=codigoseguro.com;port=3306;username=desarrollo;password=eLuv326!;database=phishingFisher";

**Comment by CodigoSeguro** [comment]
Apologies, they are just for testing, we will change them when we have a full release.
Thank you for your time.

**Comment by CodigoSeguro** [comment]
Now it's fixed, you can configure it in App.config.
