### ISSUE TITLE
Do not hardcode paths

### ISSUE THREAD

**Issue by cybercamphackathon** [CodigoSeguro/PhishingFisher#7]
SaveImage(oneSpLink, "c:/imgs/" + i + ext, returnImgFormat(ext));

This is not portable, and it's not the correct way to constrct paths which may lead to crosspath vulns and will not work on non-windows platforms

**Comment by cybercamphackathon** [comment]
This should be configurable by the user at runtime

**Comment by CodigoSeguro** [comment]
We added a config file. It's App.config and this is where the user will need to change the configurations because it will be changed by whoever runs the server. The web/extension user will not need to configure anything.
